# Dynamic Traefik Configuration for phpier Global Services
# Generated by phpier

# HTTP configuration
http:
  # Middlewares for common functionality
  middlewares:
    # Security headers
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin"

    # Development headers
    dev-headers:
      headers:
        customResponseHeaders:
          X-Dev-Environment: "phpier"
          X-Powered-By: "phpier"

    # Rate limiting (optional)
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    # CORS for development (optional)
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

  # Static routers (most routing will be automatic via Docker labels)
  routers:
    # Traefik dashboard (development only)
    api:
      rule: "Host(`traefik.{{.Global.Traefik.Domain}}`)"
      service: api@internal
      entryPoints:
        - web