# Traefik Configuration for phpier Global Services
# Generated by phpier

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points
entryPoints:
  web:
    address: ":{{.Global.Traefik.Port}}"
  websecure:
    address: ":{{.Global.Traefik.SSLPort}}"

# API and dashboard
api:
  dashboard: true
  insecure: true

# Providers
providers:
  # Docker provider for automatic service discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "{{.Global.Network}}"
    watch: true
    
  # File provider for static configuration
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Log configuration
log:
  level: "INFO"

accessLog: {}

# Metrics (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true