# PHP Version Configurations
versions:
  "5.6":
    base_image: "php:5.6-fpm"
    composer_version: "2.2"
    node_version: "16.20.2"
    supported_extensions:
      # Core extensions available in PHP 5.6
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - fileinfo
      - filter
      - ftp
      - gd
      - iconv
      - intl
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions (may need special installation)
      - redis
      - imagick
    default_settings:
      memory_limit: "128M"
      upload_max_filesize: "32M"
      post_max_size: "32M"
      max_execution_time: "300"

  "7.3":
    base_image: "php:7.3-fpm"
    composer_version: "2.2"
    node_version: "16.20.2"
    supported_extensions:
      # Core and bundled extensions
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "7.4":
    base_image: "php:7.4-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # All available extensions for 7.4
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "8.0":
    base_image: "php:8.0-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # PHP 8.0 extensions
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "8.1":
    base_image: "php:8.1-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # PHP 8.1 extensions
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "8.2":
    base_image: "php:8.2-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # PHP 8.2 extensions
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "8.3":
    base_image: "php:8.3-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # PHP 8.3 extensions (most comprehensive)
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"

  "8.4":
    base_image: "php:8.4-fpm"
    composer_version: "latest"
    node_version: "18.19.0"
    supported_extensions:
      # PHP 8.4 extensions (latest available)
      - bcmath
      - bz2
      - calendar
      - ctype
      - curl
      - dba
      - dom
      - exif
      - ffi
      - fileinfo
      - filter
      - ftp
      - gd
      - gmp
      - iconv
      - intl
      - ldap
      - mbstring
      - mysqli
      - opcache
      - openssl
      - pcntl
      - pdo
      - pdo_mysql
      - pdo_pgsql
      - pdo_sqlite
      - pgsql
      - phar
      - posix
      - readline
      - session
      - shmop
      - simplexml
      - soap
      - sockets
      - sodium
      - sqlite3
      - sysvmsg
      - sysvsem
      - sysvshm
      - tokenizer
      - xml
      - xmlreader
      - xmlwriter
      - xsl
      - zip
      - zlib
      # PECL extensions
      - redis
      - imagick
      - igbinary
      - mongodb
      - imap
      - lz4
    default_settings:
      memory_limit: "256M"
      upload_max_filesize: "64M"
      post_max_size: "64M"
      max_execution_time: "300"